version: '3.8'

services:
  amma:
    build: .
    container_name: amma-bedtime-stories
    ports:
      - "3000:3000"  # Frontend
      - "8001:8001"  # Backend API
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app
      # Add your OpenAI API key here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: amma-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - amma
    restart: unless-stopped
    profiles:
      - production
